### ISSUE TITLE
ClassicUI -2.10.1-1 for debian stretch missing

### ISSUE THREAD

**Issue by MontiMcMannus** [Icinga/icinga-packaging#118]
Hi,

my customer just updated the whole server and got icinga2 2.10.1 installed. But the classic-ui isn't available. I've seen e.g. on SID/unstable, but not at this repository. Can you provide it too?

(Before you ask: No, we don't want to install full php, sql and so on on our small monitoring server in order to get the icinga2web package).

Thanks a lot
Jan

**Comment by dnsmichi** [comment]
Classic UI packages have been deprecated in 2.7 (icinga/icinga2#5102) and removed in 2.9/2.10 (icinga/deb-icinga2#5). Icinga 1.x is EOL by the end of 2018, please plan your migration to Icinga Web 2.

**Comment by dnsmichi** [comment]
Classic UI packages have been deprecated in 2.7 (icinga/icinga2#5102) and removed in 2.9/2.10 (icinga/deb-icinga2#5). Icinga 1.x is EOL by the end of 2018, please plan your migration to Icinga Web 2.

**Comment by MontiMcMannus** [comment]
Ok, then I should look for other tools. Nagios/Icinga were fine because it was light, reliable and transparent with only few attack vectors and now I have to backup and maintain a full database, and have to keep apache and php always uptodate. Just wondering if its only to press the users into an alternative because webui 2.10 is included in debian-sid-unstable. Have to ask my customers if they want to migrate.

**Comment by dnsmichi** [comment]
This went missing somehow while GitHub had storage problems, from my inbox.

> Ok, then I should look for other tools. Nagios/Icinga were fine because it was light, reliable and transparent with only few attack vectors and now I have to backup and maintain a full database, and have to keep apache and php always uptodate. Just wondering if its only to press the users into an alternative because classicui 2.10 is included in debian-sid-unstable. Have to ask my customers if they want to migrate.

packages.debian.org is a different repository vendor, they can follow our package decisions, or not. At some point, the backend for the Classic UI will be removed from Icinga 2 as well, leaving their package non-functional.

Classic UI always was a compatibility choice, allowing users to use Icinga 2 instead of Icinga 1 while Icinga Web 2 was in development. When Icinga Web 2 became stable, we've invited our users to fully use the "2.x" world, focussing our development on it with an entire framework of modules and integrations.

There's many things which don't work with Classic UI, nor the underlaying status and log features. Ranging from notification users abused for permission in cgi.cfg to problematic historical views in clustered HA environments. Search the issue tracker and community forums for this kind of questions.

So this decision has been made with 2.7 more than one year ago, dropping the configuration package for Classic UI. You may of course manually install the old 1.x cgi package and modify the configuration on your own, up until Icinga 2 provides `statusdata` and `compatlog`.

Since 1.x is EOL, you may also want to keep an eye on security issues not being fixed then. For Icinga Web 2, rest assured that reported vulnerabilities are fixed and disclosed responsibly. Same goes for Icinga 2.

In terms of managing an application stack - I agree on the overhead with databases and additional modules, still, modern tools make intensive use of that. GitLab for instance comes with PgSQL, Redis, Ruby-on-Rails and Golang-Runners yet many people decided to move from their small Git servers. Having automation and config management tools helps here of course.

Cheers,
Michael
