### ISSUE TITLE
Packages in snapshots are older than in the release repo

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icinga-packaging#173]
hi,
I finally got around to installing the snapshots sources on one test server and was surprised to see that the icingaweb2 packages are of a lower version than they are in the release repository. I would have expected to be at least the same.

As it stands, this makes it a bit difficult to actually use the snapshot repository.

**Comment by htriem** [comment]
Hi, the packages aren't actually older. It's just the naming convention we're using - the snapshots for 2.9.0_somethingorelse_ are the latest version of 2.9, just like 2.9.3 is the latest version released. 
We will consider changing this when we overhaul our packaging, but for now this is expected behaviour and I'll close this one.
