### ISSUE TITLE
Packages for Ubuntu 20.04 LTS "focal fossa"

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga-packaging#185]
Today Ubuntu 20.04 LTS "focal fossa" was released, please provide packages for it.

This issue is mainly for tracking and awareness.

**Comment by N-o-X** [comment]
Packages for Icinga 2.11.3 are now available for 20.04.

We currently can’t provide packages for Icinga Web 2.7, because this version is not compatible with the PHP version provided by Ubuntu 20.04 (PHP 7.4). We’ll provide stable Icinga Web packages for 2.8+ when that’s released. Properly by the end of the month.

We'll also release packages for our latest testing releases in the next days.
