### ISSUE TITLE
No packages for Ubuntu 22.04 (jammy)

### ISSUE THREAD

**Issue by Virsacer** [Icinga/icinga-packaging#227]
Hi,
Ubuntu 21.10 (impish) has been released last month, but it is missing in the Icinga Package Repository. 

I thought it would be added on next release, but today with Icingaweb2 this was not the case...

**Comment by nilmerg** [comment]
Alex, I've passed this onto you, since you've began working on this last week.

**Comment by Virsacer** [comment]
Ubuntu 22.04 (jammy) has been released.

Please add packages for Icinga2 and Icingaweb2 to the jammy repo.

**Comment by julianbrost** [comment]
The last two Icinga 2 releases (2.13.3 and 2.12.7) were already built for jammy: https://packages.icinga.com/ubuntu/pool/main/i/icinga2/?C=M;O=D

**Comment by Virsacer** [comment]
But
https://packages.icinga.com/ubuntu/dists/icinga-jammy/main/binary-amd64/Packages
is empty...

**Comment by Virsacer** [comment]
Also in your linked location there are only icinga2 packages.
icinga2-bin, icinga2-common, icinga2-doc, icinga2-ido-mysql, ... are missing

**Comment by Virsacer** [comment]
According to https://git.icinga.com/packaging/deb-icinga2/-/jobs/152142 the packages are apparently uploaded somewhere.

Can you please fix it to upload them in https://packages.icinga.com/ubuntu/pool/main/i/icinga2/ ?

**Comment by Virsacer** [comment]
Is nobody able to repair the repo?

**Comment by fabricelaborie** [comment]
not finding icingadb ... is it because it is RC2 ? living in testing  which is missing ? 

Hit:6 https://packages.icinga.com/ubuntu icinga-jammy InRelease
Err:7 https://packages.icinga.com/ubuntu icinga-jammy-testing Release
  404  Not Found [IP: 185.233.189.126 443]
Reading package lists... Done
E: The repository 'https://packages.icinga.com/ubuntu icinga-jammy-testing Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://packages.icinga.com/ubuntu/dists/icinga-jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
root@icinga:~# apt-get install icingadb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package icingadb

**Comment by Virsacer** [comment]
Oh, we have some progress:
Packages for 2.12.8 appeared in jammy and impish repo :-)

Whoever did something, please do the same for 2.13.3

**Comment by fabricelaborie** [comment]
> 

oh . i had not noticed that it had installed 2.13.2...
# dpkg -l '*icinga*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-====================================================
ii  icinga2        2.13.2-1build2 amd64        host and network monitoring system
ii  icinga2-bin    2.13.2-1build2 amd64        host and network monitoring system - daemon
ii  icinga2-common 2.13.2-1build2 all          host and network monitoring system - common files
ii  icinga2-doc    2.13.2-1build2 all          host and network monitoring system - documentation
un  python-icinga2 <none>         <none>       (no description available)
ii  vim-icinga2    2.13.2-1build2 all          syntax highlighting for Icinga 2 config files in VIM

**Comment by Virsacer** [comment]
Thats the version, ubuntu ships
https://packages.ubuntu.com/jammy/icinga2

**Comment by Virsacer** [comment]
@julianbrost Thanks :-)

`jammy-testing` would also be nice to have...

**Comment by Virsacer** [comment]
`icinga-php-library` 0.9.0 is also missing

**Comment by lippserd** [comment]
We're in the middle of a release so better update your packages in some hours 😆

**Comment by Virsacer** [comment]
Thank you very much, guys!
