### ISSUE TITLE
Fedora 37 missing and ICINGA-testing.repo ERROR 404: Not Found.

### ISSUE THREAD

**Issue by LinuxPersonEC** [Icinga/icinga-packaging#271]
Any progress on Fedora 37 which has been out for a couple weeks now? Also on the testing repo:

```
wget https://packages.icinga.com/fedora/ICINGA-testing.repo -O /etc/yum.repos.d/ICINGA-testing.repo
--2022-12-05 12:18:26--  https://packages.icinga.com/fedora/ICINGA-testing.repo
Resolving packages.icinga.com (packages.icinga.com)... 185.233.189.126
Connecting to packages.icinga.com (packages.icinga.com)|185.233.189.126|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-05 12:18:29 ERROR 404: Not Found.
```

**Comment by mightbeuseless** [comment]
Hi, 

It would be nice if you can give us an ETA on this one. Because of the missing Fedora 37 Repo  we can not patch our production CoreOS Nodes. 

Nevertheless we aprreciate your work! Icinga plays a big part in our environment.

**Comment by htriem** [comment]
Our packages for Fedora 37 have been released by now, so I'll close this. Excuse the wait; we're in the process of overhauling our packaging system. 

The testing repo has been discontinued since Fedora 34, consider using the snapshot repo if so desired. Be aware: only the release repo are recommended to be run in production. 

And thanks for the nice words! Have fun using Icinga!
