### ISSUE TITLE
Source RPM missing for icinga-php-library 0.10.1-1

### ISSUE THREAD

**Issue by haxtibal** [Icinga/icinga-packaging#272]
[packages.icinga.com](https://packages.icinga.com) provides a new binary package [icinga-php-library 0.10.1-1](https://packages.icinga.com/centos/7/release/noarch/icinga-php-library/icinga-php-library-0.10.1-1.el7.noarch.rpm), but no related 0.10.1-1 source rpm. There's only the lower [0.10.0-2](https://packages.icinga.com/centos/7/release/src/icinga-php-library/icinga-php-library-0.10.0-2.el7.src.rpm).

As icingaweb2 declares [Requires:](https://git.icinga.com/packaging/rpm-icingaweb2/-/blob/master/icingaweb2.spec#L80) icinga-php-library >= 0.9.0-1, we automatically run into a `No source RPM found for icinga-php-library-0.10.1-1.el7.noarch`  error.

Seems to affect subscription repos as well.

**Comment by yhabteab** [comment]
Hi, it seems something went wrong with our upload script back then, but ever since we've had a couple of releases of the **Icinga PHP Library** and have all the corresponding source files. So I'm closing this issue as it's not worth the effort to debug and upload it years later. I hope you can understand that!
