### ISSUE TITLE
Provide packages for Debian 12 "bookworm"

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga-packaging#290]
Hello,

please provide packages for Debian 12 "bookworm". Currently only the core component `icinga2` is available for Debian 12. I'm missing for example `icingaweb2`, `icingadb`.

Thank you!

Best regards
Michael

**Comment by hasdf** [comment]
Also missing: icinga-director

**Comment by dm8tbr** [comment]
I've been dealing with untangling my install and ran into some associated issues. Mildly confusing is that debian.org seems to package things as `icingaweb2-module*`, while the icinga repository seems to use a different concept?

`icingaweb2` and `icingadb` are installable for me on debian12 "bookworm". So clearly work has been done since this ticket was created. Thanks for that!

I'm somewhat confused still as there is packaging for [icingaweb2-module-monitoring](https://packages.icinga.com/debian/pool/main/i/icingaweb2-module-monitoring/), but no build for debian 12.
This probably explains it, but I'm rusty on my deb packaging:
```
Replaces: icingaweb2-common (<< 2.12.0-1+debian12), icingaweb2-module-doc (<< 2.12.0-1+debian12), icingaweb2-module-monitoring (<< 2.12.0-1+debian12)
```

So in my current understanding this seems to be mostly converging towards *done*, but e.g. `icinga-director` is only in `icinga-bookworm-snapshots` right now. Also it might want to conflict/replace/provide(?) `icingaweb2-module-director`.

**Comment by RincewindsHat** [comment]
Basically this ticket can be closed.

@dm8tbr: I think the icinga position here is, that they are not chained to the naming scheme in debian.

**Comment by yhabteab** [comment]
Hi, we no longer use the `icingaweb2-module-*` naming scheme for our packages, but they are still available under these names if you are using the repository from Debian itself. And By now all packages for bookworm have already been uploaded, including `icinga-director`.
