### ISSUE TITLE
packages.icinga.org - source pkgs missing

### ISSUE THREAD

**Issue by cru5ad3r** [Icinga/icinga-packaging#90]
Hi, would it be possible to upload the latest icinga2 source packages to epel/7 section of the repository? I'm missing those since the version 2.6.3... Thanks a lot. ;)

**Comment by lazyfrosch** [comment]
Yes there is a bug in our RPM upload toolset.

We'll fix them asap

**Comment by lazyfrosch** [comment]
Also see https://github.com/Icinga/puppet-icinga_build/issues/44

**Comment by lazyfrosch** [comment]
This has been fixed in https://github.com/Icinga/puppet-icinga_build/commit/50d08c512b359bce1b3f091ec15625f92cc63195 and has been deployed to production.

All upcoming builds will upload the SRPM to repository.

If you need current packaging you have multiple options:
* Download them from Jenkins: https://build.icinga.com/job/icinga2-release/
* e.g. https://build.icinga.com/job/icinga2-release/job/rpm-centos-7-1binary/arch=x86_64/
* check our GIT: https://github.com/icinga/rpm-icinga2
