### ISSUE TITLE
init.conf not deleted - upgrade

### ISSUE THREAD

**Issue by wolf-in-sheeps-clothing** [Icinga/icinga-packaging#96]
OS: Ubuntu Server 16.04.4 LTS
Upgrade Icinga2 from 2.8.1 to 2.8.2

Don't know if this is the whrigt place, so if not -> sorry!

The init.conf at /etc/icinga2/ wasn't automatic deleted in the upgrade.
Is this correct?

My Testsystem is fine after upgrade and also my Prodsystem now.
I setup a new testserver with a fresh icinga installation and init.conf wasn't created. So thats fine.

Should/Could I delete the init.conf manually?

**Comment by dgoetz** [comment]
This is unfortunately the expected behavior as the file is now no longer managed by a package. 

For RPM I am sure there is no way to change this, for DEB also I think. We could do so by using a pre-script during the installation of 2.8.2 (and newer), so it removes the file during upgrade.

As the file is not changing the behavior of the service if it exists, I am not sure if we should add this pre-script. @lazyfrosch: What do you think?

**Comment by wolf-in-sheeps-clothing** [comment]
OK, thanks for the quick info. So everything is fine. I delete the init.conf manually.
Perhaps a small sentence should be included in the Upgrade Info that after upgrade to 2.8.2 the file can be deleted manually.
I think we can close here.
